const BLUEPRINT_SETUP_MIN_WIDTH = 460;
const BLUEPRINT_EMAIL_CONTENT_MIN_WIDTH = 320;
const BLUEPRINT_SPLIT_HANDLE_WIDTH = 1;

export const BLUEPRINT_WORKBENCH_SPLIT = {
	minPrimary: BLUEPRINT_SETUP_MIN_WIDTH,
	minSecondary: BLUEPRINT_EMAIL_CONTENT_MIN_WIDTH,
	defaultRatio: 0.58,
	mobileBreakpoint:
		BLUEPRINT_SETUP_MIN_WIDTH +
		BLUEPRINT_SPLIT_HANDLE_WIDTH +
		BLUEPRINT_EMAIL_CONTENT_MIN_WIDTH,
	keyboardStep: 24,
	handleWidth: BLUEPRINT_SPLIT_HANDLE_WIDTH
} as const;
