const FORMAT_STARTER_SELECTION_MIN_WIDTH = 460;
const FORMAT_EMAIL_CONTENT_MIN_WIDTH = 320;
const FORMAT_CREATOR_SPLIT_HANDLE_WIDTH = 1;

export const FORMAT_CREATOR_SPLIT = {
	minPrimary: FORMAT_STARTER_SELECTION_MIN_WIDTH,
	minSecondary: FORMAT_EMAIL_CONTENT_MIN_WIDTH,
	defaultRatio: 0.58,
	mobileBreakpoint:
		FORMAT_STARTER_SELECTION_MIN_WIDTH +
		FORMAT_CREATOR_SPLIT_HANDLE_WIDTH +
		FORMAT_EMAIL_CONTENT_MIN_WIDTH,
	keyboardStep: 24,
	handleWidth: FORMAT_CREATOR_SPLIT_HANDLE_WIDTH
} as const;
