const BUILDER_STARTING_POINT_SELECTION_MIN_WIDTH = 460;
const BUILDER_EMAIL_CONTENT_MIN_WIDTH = 320;
const BUILDER_SPLIT_HANDLE_WIDTH = 1;

export const BUILDER_WORKBENCH_SPLIT = {
	minPrimary: BUILDER_STARTING_POINT_SELECTION_MIN_WIDTH,
	minSecondary: BUILDER_EMAIL_CONTENT_MIN_WIDTH,
	defaultRatio: 0.58,
	mobileBreakpoint:
		BUILDER_STARTING_POINT_SELECTION_MIN_WIDTH +
		BUILDER_SPLIT_HANDLE_WIDTH +
		BUILDER_EMAIL_CONTENT_MIN_WIDTH,
	keyboardStep: 24,
	handleWidth: BUILDER_SPLIT_HANDLE_WIDTH
} as const;
