const BUILDER_CHAT_MIN_WIDTH = 460;
const BUILDER_EMAIL_DRAFT_MIN_WIDTH = 320;
const BUILDER_SPLIT_HANDLE_WIDTH = 1;

export const BUILDER_CANVAS_SPLIT = {
	minPrimary: BUILDER_CHAT_MIN_WIDTH,
	minSecondary: BUILDER_EMAIL_DRAFT_MIN_WIDTH,
	defaultRatio: 0.62,
	mobileBreakpoint:
		BUILDER_CHAT_MIN_WIDTH + BUILDER_SPLIT_HANDLE_WIDTH + BUILDER_EMAIL_DRAFT_MIN_WIDTH,
	keyboardStep: 24,
	handleWidth: BUILDER_SPLIT_HANDLE_WIDTH
} as const;
