export const categories = [
  { name: "Photography", icon: "📷" },
  { name: "Writing", icon: "✍️" },
  { name: "Economics", icon: "📊" },
  { name: "Health", icon: "🏥" },
  { name: "Music", icon: "🎵" },
  { name: "History", icon: "📜" },
  { name: "Psychology", icon: "🧠" },
  { name: "Education", icon: "📚" },
];

export const posts = [
  {
    id: 1,
    space: "China - World Leader.",
    spaceIcon: "assets/images/flags/zh.png",
    author: "Aya Shawn",
    authorAvatar: "",
    postedBy: "EARL 77",
    timeAgo: "Wed",
    authorTimeAgo: "2y",
    title: "Did China lose money on its bullet train project?",
    content:
      "China's 18 main trunk lines of high-speed railways, only 6 lines are profitable, and the remaining 13 are loss-making. In 2022, China's high-speed rail suffered a total loss of US$15 billion. Therefore, if all high-speed rail in China is reg",
    status: null,
    askedDate: "Dec 15, 2025",
    tableData: [
      {
        api_id: "gst-u75qm5FHGEVWFlH",
        name: "Andy Buchanan",
        first_name: "Andy",
        last_name: "Buchanan",
        email: "andrew.b@eminds.ai",
      },
      {
        api_id: "gst-FwxuJVWLWwsGyUJ",
        name: "Syed Altamash",
        first_name: "Syed",
        last_name: "Altamash",
        email: "syed.altamash@outlook.c...",
      },
      {
        api_id: "gst-qJDiH8Fh3ygqYzt",
        name: "Nikole Burke",
        first_name: "Nikole",
        last_name: "Burke",
        email: "nburke@incidentiq.com",
      },
    ],
    upvotes: 16,
    comments: 1,
  },
  {
    id: 2,
    space: "China - World Leader.",
    spaceIcon: "assets/images/flags/zh.png",
    author: "Aya Shawn",
    authorAvatar: "",
    postedBy: "EARL 77",
    timeAgo: "Wed",
    authorTimeAgo: "2y",
    title: "Did China lose money on its bullet train project?",
    content:
      "China's 18 main trunk lines of high-speed railways, only 6 lines are profitable, and the remaining 13 are loss-making. In 2022, China's high-speed rail suffered a total loss of US$15 billion. Therefore, if all high-speed rail in China is reg",
    status: "In progress",
    askedDate: "Dec 10, 2025",
    tableData: [],
    upvotes: 16,
    comments: 1,
  },
];
